#!/usr/bin/env bash
# install nginx on a remote server and configure it
sudo apt-get update 
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i 's|try_files \$uri \$uri/ =404;|try_files \$uri \$uri/ /index.html;|' /etc/nginx/sites-available/default 
sudo nginx -s reload
